#!/bin/sh

# generate instrumentation patches

printf "#Maintained by: RehabMan for: ACPIDebug\n" >instrument_Qxx.txt
printf "#instrument_Qxx.txt\n\n" >>instrument_Qxx.txt
printf "# generated by instrument.sh\n\n" >>instrument_Qxx.txt
for i in {0..255}; do
    printf "into method label _Q%02X code_regex ([\s\S]*) replace_matched\n" $i >>instrument_Qxx.txt
    printf "begin\n" >>instrument_Qxx.txt
    printf "\\\\rmdt.p1(\"EC _Q%02X enter\")" $i >>instrument_Qxx.txt; echo '\\n' >>instrument_Qxx.txt
    printf "%%1">>instrument_Qxx.txt; echo '\\n' >>instrument_Qxx.txt
    printf "\\\\rmdt.p1(\"EC _Q%02X exit\")" $i >>instrument_Qxx.txt; echo '\\n' >>instrument_Qxx.txt
    printf "end;\n\n" >>instrument_Qxx.txt
done

printf "#Maintained by: RehabMan for: ACPIDebug\n" >instrument_Lxx.txt
printf "#instrument_Qxx.txt\n\n" >>instrument_Lxx.txt
printf "# generated by instrument.sh\n\n">>instrument_Lxx.txt
for i in {0..255}; do
    printf "into method label _L%02X code_regex ([\s\S]*) replace_matched\n" $i >>instrument_Lxx.txt
    printf "begin\n" >>instrument_Lxx.txt
    printf "\\\\rmdt.p1(\"GPE _L%02X enter\")" $i >>instrument_Lxx.txt; echo '\\n' >>instrument_Lxx.txt
    printf "%%1" >>instrument_Lxx.txt; echo '\\n' >>instrument_Lxx.txt
    printf "\\\\rmdt.p1(\"GPE _L%02X exit\")" $i >>instrument_Lxx.txt; echo '\\n' >>instrument_Lxx.txt
    printf "end;\n\n" >>instrument_Lxx.txt
done

